TARGET_CPU_ABI := armeabi
TARGET_CPU_SMP := false

BOARD_EGL_CFG := device/mokoid/dma6410l/egl.cfg

USE_OPENGL_RENDERER := true

BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true
TARGET_NO_KERNEL := true

BUILD_PV_VIDEO_ENCODERS := 1
BUILD_PV_2WAY := 1
BUILD_PV_TEST_APPS := 1

ARCH_ARM_HAVE_ARMV7A := true
